name: product CI/CD

on:
  push:
    branches: ["meccar"]
    paths:
      - "product/**"
  pull_request:
    branches: ["meccar"]
    paths:
      - "product/**"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci
        working-directory: product

      - name: Formatting, linting, tsc, and tests
        run: |
          npm run format:check
          npm run lint:check
        working-directory: product
