name: product CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - 'product/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'product/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci
        
      - name: Formatting, linting, tsc, and tests
        run: |
          npm run format:write
          npm run lint:fix
