# docker-compose build && docker-compose up
version: "3"

services:

  nosql-db:
  ports:
    - ""
  container_name: nosql-db
  volumes:
    - .db/:/data/db

  products:
    build:
      dockerfile: Dockerfile
      context: ./product
    container_name: product
    ports:
      - "3003:3003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/product/node_modules
  
  accounts:
    build:
      dockerfile: Dockerfile
      context: ./account
    container_name: account
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app
      - /app/account/node_modules

  posts:
    build:
      dockerfile: Dockerfile
      context: ./post
    container_name: post
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/app  
      - /app/post/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - "3002:3002"
    restart: always
    depends_on:
      - "products"
      - "accounts"
      - "posts"
    ports:
      - "80:80"