apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
build:
  local:
    push: false

  # googleCloudBuild:
  #   projectId: taf-dev-425515

  artifacts:
    - image: us.gcr.io/taf-dev-425515/product
      context: product
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .

    - image: us.gcr.io/taf-dev-425515/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
