name: Gateway

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gateway:
    name: Authentication service
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      working-directory: gateway
      run: npm ci
    - name: Formatting, linting, tsc, and tests
      working-directory: gateway
      run: |
        npm run prettier:check
        npm run lint:check
        npm test