apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  # annotations:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: taf.dev
      http:
        paths:
          - path: /product
            pathType: Prefix
            backend:
              service:
                name: product-clusterip-srv
                port:
                  number: 8003

          - path: /api/users/?(.*)
            pathType: ImplementationSpecific
            # pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 8001