apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          # image: meccar/auth:latest (local)
          image: us.gcr.io/taf-dev-425515/auth:latest
          # envFrom:
          #   configMapRef:
          #     name: auth-config
          #   secretKeyRef:
          #     name: auth-secrets
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGODB_URI
              value: "mongodb+srv://taf-auth:<password>@tafauth.0q4qdv6.mongodb.net/?retryWrites=true&w=majority&appName=tafAuth"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-password: cXdlcnR5MTIzNDU2
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt-key: eW91cl9hY3R1YWxfand0X2tleV9oZXJl
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 8001
      targetPort: 8001
