apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: meccar/auth
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGODB_URI
              value: "mongodb+srv://taf-Auth:<password>@tafauth.suqvaxr.mongodb.net/?retryWrites=true&w=majority&appName=tafAuth"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-mongodb-secret
                  key: auth-mongodb-password
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-key
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-mongodb-secret
type: Opaque
data:
  auth-mongodb-password: VGhyZ2d1SGV5azBVR2JRTg==
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  jwt-key: |
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDHHlaUXhSdH5/n
    F2nQ5LFGM69kppS563MUQmM9zLOSSStQSa36Qb5DmUv8+BzGYAhyJ04qWjZOgzBu
    zZ6OdPgZMH2tO7AZG0HncE7K1mAU/lDuTRU223aIBToH92krLtL+d/T4BlVHSpzP
    2hfeQV0L4d18VEU2pQx2noDB2g33cU2VkObCDFYKk7PS3LjC5uW6JeEb+YqrE7Ly
    3FQxKNtlnipEMtWunDxZj6lVGkc5g2seJjKVZ6VW7bAekysQ+XLqfeJk3hh7LtRc
    LxTop/CScH7wLlUg9N0X3NysVIhWZixB6w4xbXMcIqPlWt6FMGpw5yir7ZQUNfen
    +G5EKF6BAgMBAAECggEAZNJXxIhep7B7pueUDNG/cWx6QtyWMg2mF3wGBCTCSDAE
    XoLwNOdVD6VvdIetCkVWAXclfQxwsxB6VaCHyFoxxY9oE29Fm3DRzf5v5wTlYbvj
    /sXJGB3Hxtfeqmn8NoFfFLpor62FQLPm8tfbfg5arsmO/IUvBpxL00QurflbWQ6B
    LBMiG2olkOE0VtCjG9B14Xj9fF+AfYDPR7icnp52oxyaFcwHckNT89Fg6nm6G9W/
    W8iDb/wTIcGEeDDNN2FYEJIPtfrzQIE5CSdSqReDv8kDEFdtTMxeAnRxKcOgJvfx
    dotOcQU+nH9S8Qfk5r9epGQV5561HrlIlGB2jtrogQKBgQDmAwgk5UniuzC7VSQZ
    iCvbR5myx9KF19lp+YvxRVSP62gND5bqSvbJgDtVw4IBECUMaEs2j1j898YIavQH
    d9t3oCyi4Xs87M/CmCwBYxg1leAW4RBVbytIOIk9E64cvbRZK08bUS1MMnCiYWzo
    pUlcSTgTJKPzqFWe7ymeScE9IwKBgQDdnbu/xnJ1UspeA7sjNObYsGVuWVwehbOk
    /TP2nV0kNqsmccjez+/0Rmcs177/JQyxxNp/KtgThzwY0JZ1ADHbzNTTUusOchIY
    2ECUAyNB166/v2wG0iz8MeJoT+k+lcsQMwYQCNTkPuFI+vVxsDl3iastoYsSPxUe
    ml+jbJEqCwKBgQCX6WCznYwS5zbkQvM4uardhIiKf1cXdtvtFhfLHdMfyoZKOgWe
    cCxWIQ8PMbTnJtaRP0CNpFdNnAd6/8h0NkEI3Q0d9nYCYxVEnGRT9jLDEV2TPsoe
    4vFfHZfmct0HtnMqgWQZ0p9sN9QUKuxXKvMstF8IpaZzArap5aNDG8s4qQKBgQCD
    NsgaJRJR2uIMxiLAFqtzswVrT6dWPw19a5mfs86ZCXFOguJO4kkNlb2y9E6W3MXm
    X0qLLr/e2BxCCQZ8YdAjduSv9pFL7Ug/w5KA0FbIvj4uM9VvOHQAIj0OS/oq3x/r
    CHrXdZMvTPewcT5vwMpVt4JNsy8Xb5g+lWJ47WgJvwKBgQC4L/mfCX//UrqNJ3o7
    XDmzBptcPlSCgNhq3VVS75ASL18rQOc2rVM57H3zdIf7qY9Lu20nhI9c3EgD24Ue
    kZtkVvTa/i0u6SkxDepv39MuXgmEx/mlWEIoRKsUqMq8P3gVoLKqeX+Qiy+ICUOP
    ZxF0CKFp7cSA9TxL/H/CC3cmcA==
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 8001
      targetPort: 8001
