apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          # image: us.gcr.io/taf-dev-425515/product:latest
          image: meccar/product:latest
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGODB_URI
              value: "mongodb+srv://taf:<password>@atlascluster.wetplea.mongodb.net/"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password

---
apiVersion: v1
kind: Service
metadata:
  name: product-clusterip-srv
spec:
  selector:
    app: product
  type: ClusterIP
  ports:
    - name: product
      protocol: TCP
      port: 8003
      targetPort: 8003
