apiVersion: v1
kind: Service
metadata:
  name: product-srv
spec:
  selector:
    app: product
  type: NodePort
  ports:
    - name: product
      protocol: TCP
      port: 3003
      targetPort: 3003
