name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  auth:
    name: Authentication service
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: List directory contents
      run: ls -la
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: /home/runner/.npm/package-lock.json
    - name: Install packages
      working-directory: auth
      run: npm ci
    - name: Formatting, linting, tsc, and tests
      working-directory: auth
      run: |
        npm run prettier:check
        npm run lint:check
        npm test