name: product CI/CD

on:
  push:
    branches: [main]
    # paths:
    #   - 'product'
  pull_request:
    branches: [main]
    # paths:
      # - 'product'

jobs:
  build:
    env:
      CI: true
      # MONGO_URL: 

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: ubuntu-latest
        node-version: [21.x]
        # mongodb-version: ['6.0', '7.0', '8.0']

    name: Build and Test
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Set up Docker Buildx
    #   working-directory: product
    #   run: docker buildx create --use

    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 

    - name: Log in to Docker Hub
      run: | 
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      working-directory: product
      timeout-minutes: 10
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/product:latest

    - name: Verify Docker image
      working-directory: product
      run: docker images ${{ secrets.DOCKER_USERNAME }}/product:latest

    - name: Install packages
      working-directory: product
      run: npm ci

    - name: Formatting, linting, tsc, and tests
      working-directory: product
      run: |
        npm run format:check
        npm run lint:check
      
    # - name: Start MongoDB
    #   uses: supercharge/mongodb-github-action@1.11.0
    #   with:
    #     mongodb-version: ${{ matrix.mongodb-version }}

    - run: npm install